/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const computed: typeof import('vue')['computed']
  const defineEmit: typeof import('vue')['defineEmit']
  const defineModel: typeof import('vue')['defineModel']
  const defineProps: typeof import('vue')['defineProps']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const onMounted: typeof import('vue')['onMounted']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const useLink: typeof import('vue-router')['useLink']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { StoreDefinition } from 'pinia'
  import('pinia')
  // @ts-ignore
  export type { Ref, Reactive } from 'vue'
  import('vue')
  // @ts-ignore
  export type { RouteComponent, RouteRecordRaw } from 'vue-router'
  import('vue-router')
}
